#!/usr/bin/env node
/**
 * build.mjs — bundles the React text layer.
 *
 * Wrapper around esbuild so the command is the same from anywhere and the
 * node_modules lookup does not depend on the caller's cwd.
 *
 * Usage:  node mem/build.mjs [--watch]
 */

import { spawnSync } from "node:child_process";
import { fileURLToPath } from "node:url";
import { dirname, resolve } from "node:path";
import { existsSync, readFileSync, writeFileSync } from "node:fs";

const __dirname = dirname(fileURLToPath(import.meta.url));
const repo = resolve(__dirname, "..");
const esbuild = resolve(repo, "node_modules", ".bin", process.platform === "win32" ? "esbuild.cmd" : "esbuild");

if (!existsSync(esbuild)) {
  console.error(`esbuild not found at ${esbuild}\nRun npm install in the repo root first.`);
  process.exit(1);
}

// --config <file.json> bakes a config into the bundle; without it the bundle
// runs the hand-authored mem timeline.
const ci = process.argv.indexOf("--config");
const configPath = ci >= 0 ? resolve(process.argv[ci + 1]) : null;
// esbuild's --define needs a single-line JS literal, so the config goes in as a
// generated module instead. Regenerated on every build so a stale one from a
// previous --config run cannot silently leak into a plain build.
const generated = resolve(__dirname, "text-layer", "src", "_config.generated.js");
writeFileSync(generated,
  configPath
    ? `// GENERATED by mem/build.mjs from ${configPath}. Do not edit.
`
      + `export default ${JSON.stringify(JSON.parse(readFileSync(configPath, "utf8")), null, 2)};
`
    : `// GENERATED by mem/build.mjs — no --config given.
export default null;
`,
  "utf8");

const args = [
  resolve(__dirname, "text-layer", "src", "index.jsx"),
  "--bundle",
  `--outfile=${resolve(__dirname, "text-layer", "dist", "bundle.js")}`,
  "--loader:.jsx=jsx",
  "--jsx=automatic",
  "--format=iife",
  "--log-level=warning",
];
if (process.argv.includes("--watch")) args.push("--watch");

const r = spawnSync(esbuild, args, { stdio: "inherit", shell: process.platform === "win32" });
if (r.status !== 0) process.exit(r.status ?? 1);
console.log(`built mem/text-layer/dist/bundle.js${configPath ? ` (config: ${configPath})` : " (hand-authored timeline)"}`);
